### ISSUE TITLE
Add text to bubble.

### ISSUE THREAD

**Issue by sirvon** [vladaverin24/DynamicBubble#1]
Is there any way to just add text or objects to the bubble when its drawn?

thanks!

**Comment by 0xNSHuman** [comment]
Hi @sirvon!

There is no way to add anything but text to bubbles currently.
And current implementation makes text editing available through user taps only.

However, it should be relatively easy to make it possible to set text programmatically. Check out **[`textView`](https://github.com/vladaverin24/DynamicBubble/blob/master/DynamicBubble/DynamicBubble.swift#L426)** property in the `DynamicBubble.swift`, it's the text view representing bubble text. You can try to create a public method that takes a string and updates `textView.text` with it. I believe bubble should catch up and autoresize itself.

Let me know if this helps.
